openapi: "3.0.0"
info:
  version: 1.0.0
  title: Winner's Habit
  license:
    name: Wave
servers:
  - url: http://grabtest.tk:4240
    description: Hi! My name is dongho
tags:
  - name: challenge
    description: about challenge
  - name: habit
    description: habit apis
  - name: user
    description: user apis
  - name: winner
    description: winner apis
paths:
  '/challenge':
    get:
      tags:
        - challenge
      summary: "{userId}가 속한 챌린지의 습관들 불러오기" 
      parameters:
        - name: user_id
          in: query
          description: PK of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ChallengeInfo"
        '404':
          description: Challenge Not Found
  '/habit/{habitId}':
    get:
      tags:
        - habit
      summary: 유저의 특정 습관의 상세 정보 불러오기
      description: return HabitDetail
      parameters:
        - name: habitId
          in: path
          description: PK of habit
          required: true
          schema:
            type: integer
        - name: user_id
          in: query
          description: PK of user
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: success to bring habit details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HabitDetail" 
  '/allChallenges':
    get:
      tags:
        - challenge
      summary: 모든 챌린지 리스트 가져오기
      responses:
        '200':
          description: success to bring all habits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Challenge"
  '/habit-history':
    get:
      tags:
        - habit
      summary: userId, date에 해당하는 습관의 히스토리 가져오기
      parameters:
        - name: user_id
          in: query
          description: PK of user
          required: true
          schema:
            type: integer
        - name: date
          in: query
          description: date which user want to show history of habits
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success to bring habit histories
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/HabitHistory"
components:
  schemas:
    User:
      title: a User
      description: A User who is going to participate in challenge
      type: object
      required:
        - id
        - username
        - pw
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        pw:
          type: string
    Habit:
      title: a habit used in home page
      description: "홈 페이지에서 보여주는 용. 자세한 정보는 없음"
      type: object
      required:
        - habitId
        - habitName
        - icon
        - color
        - alarmFlag
      properties:
        habitId:
          type: integer
          format: int64
        habitName: 
          type: string
        icon:
          type: string
        color:
          type: string
        defaultAttributeValue:
          type: integer
          format: int64
        attribute:
          type: string
          description: "습관 고유 성질. 예로 기상 습관은 성공/실패, 운동 습관은 0/20분 등등"
        alarmFlag:
          type: boolean
        alarmTime:
          type: string
          description: "form; 06:30:20"
    HabitDetail:
      description: 세부 습관 페이지에서 보여주는 습관
      type: object
      required:
        - userHabitId
        - createDate
        - alarmFlag
      properties:
        userHabitId:
          type: integer
        createDate:
          type: string
        alarmFlag:
          type: boolean
        alarmTime:
          type: string
          description: "form; 06:30:00"
        alarmMusic:
          type: string
        alarmHaptic:
          type: string
        repeatMon:
          type: boolean
        repeatTue:
          type: boolean
        repeatWed:
          type: boolean
        repeatThu:
          type: boolean
        repeatFri:
          type: boolean
        repeatSat:
          type: boolean
        repeatSun:
          type: boolean
        memo:
          type: string
        history:
          type: array
          items:
            $ref: "#/components/schemas/HabitHistory"
    ChallengeInfo:
      title: an information of current challenge
      description: "홈 페이지에서 보여주는 용. 챌린지 이름, d-day, 광고, 등등 포함 가능"
      type: object
      required:
        - result
      properties:
        result:
          type: boolean
        challenge:
          $ref: "#/components/schemas/Challenge"
        habits:
          type: array
          items:
            # type: object
            $ref: '#/components/schemas/Habit'
    HabitHistory:
      description: a single history of habit
      type: object
      required:
        - habitId
        - doneFlag
      properties:
        habitId:
          type: integer
        date:
          type: string
        doneFlag:
          type: boolean
    Challenge:
      description: info of sigle challenge
      type: object
      required:
        - challengeId
        - challengeName
        - challengeImage
      properties:
        challengeId:
          type: integer
        challengeName:
          type: string
        challengeImage:
          type: string
        challengeDDay:
          type: integer
      

          
         

